project.created=Subhabrata
jwt.access.secret=6a1d9fcb4a0e87b92f0d8d4c1b9e74b3a8f1c9e2d7b5f6a4c3e8d9f0a1b2c3d4
jwt.access.expiration=900000
jwt.refresh.expiration=604800000
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
